from enum import Enum

class WebFailureType(Enum):
    SELECTOR_NOT_FOUND = "SELECTOR_NOT_FOUND"
    ELEMENT_NOT_VISIBLE = "ELEMENT_NOT_VISIBLE"
    INTERCEPTED = "INTERCEPTED"
    STALE_PROMISE = "STALE_PROMISE"
    NAVIGATION_CHANGED = "NAVIGATION_CHANGED"
    TIMEOUT = "TIMEOUT"
    POLICY_DENIED = "POLICY_DENIED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"
